# Generated by Django 4.2.5 on 2023-10-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='bank_img', verbose_name='Изображение'),
        ),
    ]
