# Generated by Django 4.2.5 on 2023-10-09 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_bank_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255, verbose_name='Тип точки')),
            ],
        ),
        migrations.RenameField(
            model_name='workload',
            old_name='title',
            new_name='workload_name',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='can_deposit_money',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='can_withdraw_cash',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='employees',
        ),
        migrations.AddField(
            model_name='bank',
            name='end_time',
            field=models.TimeField(default='00:00', verbose_name='Время закрытия'),
        ),
        migrations.AddField(
            model_name='bank',
            name='for_lm',
            field=models.BooleanField(default=False, verbose_name='Оборудован для маломобильных граждан'),
        ),
        migrations.AddField(
            model_name='bank',
            name='for_visually_impaired',
            field=models.BooleanField(default=False, verbose_name='Оборудован для слабовидящих'),
        ),
        migrations.AddField(
            model_name='bank',
            name='nfc',
            field=models.BooleanField(default=False, verbose_name='Возможность оплаты по NFC'),
        ),
        migrations.AddField(
            model_name='bank',
            name='put_rubles',
            field=models.BooleanField(default=False, verbose_name='Возможность положить наличные рубли'),
        ),
        migrations.AddField(
            model_name='bank',
            name='qr_payment',
            field=models.BooleanField(default=False, verbose_name='Возможность совершать операции по QR коду'),
        ),
        migrations.AddField(
            model_name='bank',
            name='start_time',
            field=models.TimeField(default='00:00', verbose_name='Время открытия'),
        ),
        migrations.AddField(
            model_name='bank',
            name='withdraw_qr',
            field=models.BooleanField(default=False, verbose_name='Возможность снять наличные по QR коду'),
        ),
        migrations.AddField(
            model_name='bank',
            name='withdraw_rubles',
            field=models.BooleanField(default=False, verbose_name='Возможность снять наличные рубли'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='workload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='banks.workload', verbose_name='Статус загруженности'),
        ),
        migrations.AddField(
            model_name='bank',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='banks.types', verbose_name='Тип точки'),
        ),
    ]
