# Generated by Django 4.2.5 on 2023-10-14 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_types_rename_title_workload_workload_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='workload',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='banks.workload', verbose_name='Статус загруженности'),
        ),
    ]
